export const LOADING_PHRASES = [
  "Brewing coffee",
  "Summoning pixels",
  "Compiling vibes",
  "Tidying up",
  "Polishing",
  "Untangling wires",
  "Feeding the hamsters",
  "Warming up",
  "Aligning the stars",
  "Reticulating splines",
  "Waking the servers",
  "Dusting off pixels",
  "Charging crystals",
  "Counting to infinity",
  "Stretching the canvas",
  "Booting neurons",
  "Chasing electrons",
  "Petting the cat",
  "Loading good vibes",
  "Plotting the grid",
  "Greasing the gears",
  "Folding the origami",
  "Tuning the synths",
  "Brewing more coffee",
];
