export const SKILL_ICON_MAP: Record<string, string> = {
  Typescript: "devicon:typescript",
  Javascript: "devicon:javascript",
  Nuxtjs: "devicon:nuxt",
  TailwindCSS: "devicon:tailwindcss",
  Bootstrap: "devicon:bootstrap",
  Vuejs: "devicon:vuejs",
  React: "devicon:react",
  Nextjs: "devicon:nextjs",
  Laravel: "devicon:laravel",
  Adonisjs: "devicon:adonisjs",
  Nodejs: "devicon:nodejs",
  PHP: "devicon:php",
  MySQL: "devicon:mysql",
  PostgreSQL: "devicon:postgresql",
  MongoDB: "devicon:mongodb",
  Github: 'devicon:github',
  Gitlab: 'devicon:gitlab',
  Express: 'devicon:express',
  Strapi: 'logos:strapi-icon',
  Python: 'devicon:python',
  Flask: 'devicon:flask',
  jQuery: 'devicon:jquery',
  Storybook: 'devicon:storybook',
  Vitest: 'devicon:vitest',
  Supabase: 'devicon:supabase',
  Figma: 'devicon:figma',
};

export const skills = [
  'Typescript',
  'Javascript',
  'TailwindCSS',
  'Bootstrap',
  'Vuejs',
  'Nuxtjs',
  'React',
  'Nextjs',
  // 'Pinia',
  'PHP',
  'Laravel',
  'Nodejs',
  'Express',
  'Adonisjs',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Supabase',
  'Python',
  "Github",
  "Gitlab",
  "Strapi",
  "Figma",
  "Storybook",
  'Vitest',
]
